const headerComment = `
 * This file has been generated by Babel.
 * DO NOT EDIT IT DIRECTLY
 * Edit the JS source file src/js/push.js
 `;

module.exports = {
  presets: [
    '@babel/preset-env'
  ],
  plugins: [
    function addHeader () {
      return {
        visitor: {
          Program (path) {
            path.addComment(
              'leading',
              headerComment
            );
          }
        }
      };
    }
  ]
};
